/**
 * Auto-generated type definitions from JSON configuration files
 * Generated from: /Users/benoitgasnier/Documents/Site/ERP/erp-vitrine/config
 * DO NOT EDIT MANUALLY - This file is automatically generated
 * Generated hash: 7eebf0d41f1bc14cad927673cac091f4
 */

// Export direct du schema généré (Prisma-style)
export interface GeneratedConfigSchema {
  readonly app: {
    readonly name: 'NextNode Frontend'
    readonly version: '1.0.0'
    readonly features: readonly (string)[]
    readonly environment: 'default' | 'dev' | 'local' | 'prod' | 'test'
  }
  readonly email: {
    readonly provider: 'resend'
    readonly from: 'noreply@nextnode.dev' | 'onboarding@resend.dev' | 'test@example.com'
    readonly to: 'contact@nextnode.dev' | 'walidmostefaoui@nextnode.fr' | 'test@example.com'
    readonly replyTo: 'support@nextnode.dev'
    readonly templates: {
      readonly projectRequest: {
        readonly subject: 'Nouvelle demande de projet : {{projectName}}' | '[DEV] Nouvelle demande de projet : {{projectName}}' | '[TEST] Projet test : {{projectName}}'
        readonly companyName: 'NextNode' | 'Test Company'
        readonly websiteUrl: 'https://nextnode.dev' | 'https://nextnode-front-dev.fly.dev' | 'http://localhost:4321' | 'https://test.example.com'
        readonly companyLogo: null
      }
    }
  }
}

// Module augmentation pour remplacer ConfigSchema
declare module '@nextnode/config-manager' {
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  interface ConfigSchema extends GeneratedConfigSchema {}
}

export {}
